In [1]:
from google.colab import files
uploaded = files.upload()

Saving tested.csv to tested.csv

In [50]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [51]:
df = pd.read_csv("tested.csv")
df.sample(10)

     PassengerId  Survived  Pclass  ...      Fare Cabin  Embarked
313         1205         1       3  ...    7.7500   NaN         Q
79           971         1       3  ...    7.7500   NaN         Q
386         1278         0       3  ...    7.7750   NaN         S
251         1143         0       3  ...    7.9250   NaN         S
398         1290         0       3  ...    7.7750   NaN         S
377         1269         0       2  ...   11.5000   NaN         S
278         1170         0       2  ...   21.0000   NaN         S
102          994         0       3  ...    7.7500   NaN         Q
314         1206         1       1  ...  135.6333   C32         C
161         1053         0       3  ...   15.2458   NaN         C

[10 rows x 12 columns]

In [52]:
df.isnull().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [53]:
df.drop(columns=["Cabin","PassengerId","Name","Ticket","Fare"], inplace=True)
df["Family"] = df["SibSp"] + df["Parch"]
df.drop(columns=["SibSp","Parch"], inplace=True)

In [54]:

df["Family"].value_counts()

Family
0     253
1      74
2      57
3      14
4       7
10      4
6       4
5       3
7       2
Name: count, dtype: int64

In [83]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(df.drop("Survived",axis = 1), df["Survived"], test_size=0.2, random_state=42)

In [74]:
x_train

     Pclass     Sex   Age Embarked  Family
282       3  female   NaN        Q       0
367       3  female  22.0        S       0
301       2    male   NaN        C       0
153       3  female  36.0        S       2
219       3    male   NaN        S       0
..      ...     ...   ...      ...     ...
323       1    male  33.0        S       0
192       3    male  11.5        S       2
117       3  female   1.0        S       2
47        3    male   NaN        Q       0
172       3    male  23.0        S       1

[376 rows x 5 columns]

In [75]:
y_train

282    1
367    1
301    0
153    1
219    0
      ..
323    0
192    0
117    1
47     0
172    0
Name: Survived, Length: 376, dtype: int64

In [76]:
cle = ColumnTransformer(transformers=[
    ("age_imp", SimpleImputer(strategy='mean'), ["Age"]),
    ("sex_emb", OneHotEncoder(drop="first", sparse_output=False), ["Sex","Embarked"]),

    ("scale", StandardScaler(), ["Age","Family"]),

], remainder="passthrough")

In [87]:
cle.fit_transform(x_train).shape

(334, 7)

In [88]:
dfc = DecisionTreeClassifier()
dfc.fit(cle.fit_transform(x_train), y_train)

DecisionTreeClassifier()

In [89]:
y_pred = dfc.predict(cle.transform(x_test))

In [90]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [91]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

In [92]:
y_test

321    0
324    1
388    0
56     0
153    1
      ..
57     0
126    0
24     1
17     0
66     1
Name: Survived, Length: 84, dtype: int64